apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-volume-claim
  labels:
    app: elasticsearch
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.6
        imagePullPolicy: Always
        ports:
        - containerPort: 9200
        - containerPort: 9300
        env:
        - name: xpack.security.enabled
          value: "false"
        - name: discovery.type
          value: "single-node"
        volumeMounts:
        - name: elasticsearch-volume
          mountPath: /usr/share/elasticsearch/data
      volumes:
      - name: elasticsearch-volume
        persistentVolumeClaim:
          claimName: elasticsearch-volume-claim
      initContainers:
      - name: file-permissions
        image: busybox
        command: ['chown', '-R', '1000:1000', '/usr/share/elasticsearch/']
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: elasticsearch-volume
        securityContext:
          privileged: true
          runAsUser: 0
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
spec:
  selector:
    app: elasticsearch 
  ports:
    - name: es1
      protocol: TCP
      port: 9200
      targetPort: 9200
    - name: es2
      protocol: TCP
      port: 9300
      targetPort: 9300

