apiVersion: v1
kind: ConfigMap
metadata:
  name: php-configmap
data:
  server-url: php-service
  filebeat.yml: |
    filebeat:
      config:
        modules:
          path: /usr/share/filebeat/modules.d/*.yml
          reload:
            enabled: true
      modules:
      - module: apache2
        access:
          var.paths: ["/var/log/apache2/access.log*"]
        error:
          var.paths: ["/var/log/apache2/error.log*"]
    output:
      logstash:
        hosts: ["logstash-service:5044"]
