apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    app: php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - name: php
        image: remusnastasa/my-php
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: MYSQL_USER
          valueFrom: 
            configMapKeyRef:
              name: mysql-configmap
              key: username
        - name: MYSQL_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
        - name: MYSQL_SERVER
          valueFrom: 
            configMapKeyRef:
              name: mysql-configmap
              key: server-url
        - name: MYSQL_DATABASE
          valueFrom: 
            configMapKeyRef:
              name: mysql-configmap
              key: database-name
        volumeMounts:
        - name: apache-logs
          mountPath: /var/log/apache2/
      - name: filebeat-sidecar
        image: docker.elastic.co/beats/filebeat:7.17.6
        volumeMounts:
        - name: apache-logs
          mountPath: /var/log/apache2/
        - name: filebeat-config
          mountPath: /usr/share/filebeat/filebeat.yml
          subPath: filebeat.yml
      volumes:
      - name: apache-logs
        emptyDir: {}
      - name: filebeat-config
        configMap:
          name: php-configmap
          items:
          - key: filebeat.yml
            path: filebeat.yml
---
apiVersion: v1
kind: Service
metadata:
  name: php-service
spec:
  selector:
    app: php 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

